return {
	UI = {
		"Frame",
		"TextLabel",
		"TextButton",
		"TextBox",
		"ImageLabel",
		"ImageButton",
		"ScrollingFrame",
		"CanvasGroup",
		"UICorner",
		"UIStroke",
		"UIGradient",
		"UIListLayout",
		"UIGridLayout",
		"UIPageLayout",
		"UITableLayout",
		"UIPadding",
		"UIScale",
		"UISizeConstraint",
		"UITextSizeConstraint",
		"UIAspectRatioConstraint",
		"ViewportFrame"
	},

	Scripting = {
		"Script",
		"LocalScript",
		"ModuleScript",
		"RemoteEvent",
		"RemoteFunction",
		"BindableEvent",
		"BindableFunction",
	},
	
	Value = {
		"ObjectValue",
		"StringValue",
		"IntValue",
		"NumberValue",
		"BoolValue",
		"Vector3Value",
		"CFrameValue",
		"Color3Value",
		"BrickColorValue",
		"RayValue"
	},

	Parts = {
		"Part",
		"WedgePart",
		"CornerWedgePart",
		"TrussPart",
		"UnionOperation",
		"NegateOperation",
		"MeshPart"
	},

	Lighting = {
		"PointLight",
		"SpotLight",
		"SurfaceLight",
		"Sky",
		"Atmosphere",
		"Clouds",
		"SunRaysEffect",
		"BloomEffect",
		"BlurEffect",
		"ColorCorrectionEffect",
		"DepthOfFieldEffect"
	},

	Constraints = {
		"AlignOrientation",
		"AlignPosition",
		"AngularVelocity",
		"LineForce",
		"VectorForce",
		"Attachment",
		"BallSocketConstraint",
		"HingeConstraint",
		"PrismaticConstraint",
		"CylindricalConstraint",
		"RodConstraint",
		"RopeConstraint",
		"SpringConstraint",
		"WeldConstraint",
		"RigidConstraint",
		"NoCollisionConstraint",
		"UniversalConstraint"
	},

	Sounds = {
		"Sound",
		"SoundGroup",
		"ChorusSoundEffect",
		"CompressorSoundEffect",
		"DistortionSoundEffect",
		"EchoSoundEffect",
		"EqualizerSoundEffect",
		"FlangeSoundEffect",
		"PitchShiftSoundEffect",
		"ReverbSoundEffect",
		"TremoloSoundEffect"
	},

	Meshes = {
		"SpecialMesh",
		"BlockMesh",
		"CylinderMesh",
		"FileMesh"
	},

	Textures = {
		"Texture",
		"Decal",
		"SurfaceGui",
		"BillboardGui",
		"ScreenGui"
	},

	Gameplay = {
		"Spawn",
		"SpawnLocation",
		"Team",
		"Seat",
		"VehicleSeat",
		"Tool",
		"HopperBin",
		"Backpack",
		"StarterGui",
		"StarterPack",
		"StarterPlayer",
		"Flag",
		"FlagStand"
	},

	Humanoid = {
		"Humanoid",
		"HumanoidDescription",
		"Accessory",
		"Hat",
		"Shirt",
		"Pants",
		"ShirtGraphic",
		"BodyAngularVelocity",
		"BodyForce",
		"BodyPosition",
		"BodyThrust",
		"BodyVelocity",
		"RocketPropulsion"
	},

	Animation = {
		"Animation",
		"AnimationController",
		"Keyframe",
		"KeyframeSequence",
		"Motor6D",
		"Weld",
	},

	Grouping = {
		"Model",
		"Folder",
		"Configuration",
		"Camera"
	},

	Effects = {
		"Explosion",
		"Fire",
		"Smoke",
		"Sparkles",
		"ParticleEmitter",
		"Trail",
		"Beam",
	},
	
	Adornments = {
		"SelectionBox",
		"SelectionSphere",
		"Handles",
		"ArcHandles",
		"SurfaceSelection"
	},

	Physics = {
		"BodyAngularVelocity",
		"BodyForce",
		"BodyPosition",
		"BodyThrust",
		"BodyVelocity",
		"RocketPropulsion",
		"AssemblyAngularVelocity",
		"AssemblyLinearVelocity"
	},
} :: {[string]: {string}}