-- All commented services are created manually
return {
	game:GetService("Workspace"),
	game:GetService("Players"),
	game:GetService("CoreGui"),
	game:GetService("Lighting"),
	game:GetService("MaterialService"),
	game:GetService('NetworkClient'),
	game:GetService('PluginGuiService'),
	game:GetService('ReplicatedFirst'),
	game:GetService('ReplicatedStorage'),
	game:GetService('ServerScriptService'),
	game:GetService('ServerStorage'),
	game:GetService('StarterGui'),
	game:GetService('StarterPack'),
	game:GetService('StarterPlayer'),
	game:GetService('Teams'),
	game:GetService('SoundService'),
	game:GetService('TextChatService')
}